routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware("auth:web");

Route::group([
	"middleware" => "auth:web",
], function () {
	Route::resource("organizations", "OrganizationsController");
	Route::get("organizations/{organization}/users", "OrganizationsController@assignUsers")->name("organizations.assign-users");
	Route::post("organizations/{organization}/users", "OrganizationsController@updateUsers")->name("organizations.assign-users");

	Route::resource("organizations.chats", "ChatController");

	Route::resource("users", "UsersController");
	Route::get("users/{user}/organizations", "UsersController@assignOrganizations")->name("users.assign-orgs");
	Route::post("users/{user}/organizations", "UsersController@updateOrganizations")->name("users.assign-orgs");

	Route::get("chats/all", "ChatController@all")->name("chats.all");
});

app/Chat.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Chat extends Model {

	const FOLLOW_UP_REQUIRED = "FOLLOW UP REQUIRED";
	const SCHEDULED = "SCHEDULED";
	const NOT_SCHEDULED = "NOT SCHEDULED";

	protected $fillable = [
		'organization_id',
		'patient',
		'dob',
		'insurer',
		'email',
		'phone',
		'appointment_reason',
		'past_medical_history',
		'transcript',
		'status',
	];

	public function setDobAttribute($value) {
		$this->attributes['dob'] = Carbon::parse($value);
	}

	public function organization() {
		return $this->belongsTo(Organization::class);
	}

	public function agent() {
		return $this->hasOne(User::class, "user_id");
	}

}

app/Organization.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organization extends Model {
	protected $fillable = [
		'name',
	];

	public function users() {
		return $this->belongsToMany(User::class);
	}

	public function chats() {
		return $this->hasMany(Chat::class);
	}
}

app/User.php
<?php

namespace App;

use Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable {

	const ADMIN_ROLE = "ADMIN";
	const AGENT_ROLE = "AGENT";
	const CUSTOMER_ROLE = "CUSTOMER";

	use Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name', 'email', 'password', 'type',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password', 'remember_token',
	];

	public function getIsAdminAttribute($value) {
		return $this->attributes['type'] === self::ADMIN_ROLE;
	}

	public function getIsAgentAttribute($value) {
		return $this->attributes['type'] === self::AGENT_ROLE;
	}

	public function setPasswordAttribute($value) {
		$this->attributes['password'] = Hash::make($value);
	}

	public function chats() {
		return $this->hasMany(Chat::class);
	}

	public function organizations() {
		return $this->belongsToMany(Organization::class);
	}

}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\Chat;
use App\Http\Requests\Chat\CreateChat;
use App\Organization;
use Illuminate\Http\Request;

class ChatController extends Controller {

	public function all() {
		// Get chat of all the organizations that user has access to
	}

	public function index(Organization $organization) {
		$chats = $organization->chats()->latest()->get();

		return view("chats.index", compact("chats", "organization"));
	}

	public function create(Organization $organization) {
		return view("chats.create", ["chat" => new Chat, "organization" => $organization]);
	}

	public function store(CreateChat $request, Organization $organization) {
		$chat = new Chat($request->all());
		$chat->organization_id = $organization->id;

		auth()->user()->chats()->save($chat);

		return redirect()->route("organizations.chats.index", $organization->id);
	}

	public function edit(Request $request, Chat $chat, Organization $organization) {
		return view("chats.edit", compact('chat', 'organization'));
	}

	public function update(Request $request, Chat $chat, Organization $organization) {
		$chat->update($request->all());

		return redirect()->route("organizations.chats.index", $organization->id);
	}

	public function destroy(Chat $chat, Organization $organization) {
		$chat->delete();

		return redirect()->route("organizations.chats.index", $organization->id);
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SearchStatsRequest;
use App\Organization;

class HomeController extends Controller {

	public function index(SearchStatsRequest $request) {
		// Find all the organizations user has access to.
		if (auth()->user()->isAdmin or auth()->user()->isAgent) {
			$orgs = Organization::with(['chats' => function ($q) use ($request) {
				if ($request->has('from')) {
					$q->where("created_at", '>=', $request->get("from"))->where("created_at", '<=', $request->get("to"));
				}
			}])->get();
		} else {
			$orgs = auth()->user()->organizations()->with(['chats' => function ($q) use ($request) {
				if ($request->has('to')) {
					$q->where("created_at", '>=', $request->get("from"))->where("created_at", '<=', $request->get("to"));
				}
			}])->get();
		}

		return view('home', compact('orgs'));
	}
}

app/Http/Controllers/OrganizationsController.php
<?php

namespace App\Http\Controllers;

use App\Organization;
use App\User;
use Illuminate\Http\Request;

class OrganizationsController extends Controller {

	public function index() {
		$orgs = Organization::all();

		return view("organizations.index", compact("orgs"));
	}

	public function create() {
		return view("organizations.create", ["organization" => new Organization]);
	}

	public function store(Request $request) {
		$org = new Organization($request->all());

		$org->save();

		return redirect()->route("organizations.index");
	}

	public function edit(Request $request, Organization $organization) {
		return view("organizations.edit", compact('organization'));
	}

	public function update(Request $request, Organization $organization) {
		$organization->update($request->all());

		return redirect()->route("organizations.index");
	}

	public function destroy(Organization $organization) {
		$organization->delete();

		return redirect()->route("organizations.index");
	}

	public function assignUsers(Request $request, Organization $organization) {
		$users = User::whereType(User::CUSTOMER_ROLE)->get();
		$user_orgs = $organization->users->pluck('id')->toArray();

		return view("organizations.assign_users", compact("users", "organization", "user_orgs"));
	}

	public function updateUsers(Request $request, Organization $organization) {
		$organization->users()->sync($request->get('users', []));

		return redirect()->route("organizations.index");
	}
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\CreateUser;
use App\Http\Requests\User\DeleteUser;
use App\Http\Requests\User\UpdateUser;
use App\Organization;
use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller {
	public function index() {
		$users = User::all();

		return view("users.index", compact("users"));
	}

	public function create() {
		return view("users.create", ["user" => new User]);
	}

	public function store(CreateUser $request) {
		$org = new User($request->all());

		$org->save();

		return redirect()->route("users.index");
	}

	public function edit(Request $request, User $user) {
		return view("users.edit", compact('user'));
	}

	public function update(UpdateUser $request, User $user) {
		$user->update($request->all());

		return redirect()->route("users.index");
	}

	public function destroy(DeleteUser $request, User $user) {
		$user->delete();

		return redirect()->route("users.index");
	}

	public function assignOrganizations(Request $request, User $user) {
		$orgs = Organization::all();
		$user_orgs = $user->organizations->pluck('id')->toArray();

		return view("users.assign_organizations", compact("orgs", "user", "user_orgs"));
	}

	public function updateOrganizations(Request $request, User $user) {
		$user->organizations()->sync($request->get('organizations', []));

		return redirect()->route("users.index");
	}
}

resources/views/chats/create.blade.php
@extends('layouts.app')


@section("page_title", "New Chat for {$organization->name}")

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ route("organizations.chats.index", $organization->name) }}">Chats for {{ $organization->name }}</a></li>
    <li class="breadcrumb-item active">New Chat</li>
</ol>
@stop

@section("content")
<div class="card">
    <div class="card-body">
        {{ Form::model($chat, ['route' => ['organizations.chats.store', $organization->id]], ["class" => "form"]) }}

            <div class="row">
                <div class="col-4">
                    <div class="form-group {{ $errors->has('patient') ? 'has-error' : '' }}">
                        {{ Form::label('patient', 'Patient') }}
                        {{ Form::text('patient', null, ['class' => 'form-control', 'placeholder' => 'Jack Appleseed', 'autofocus' => true]) }}

                        @foreach ($errors->get('patient', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>

                <div class="col-4">
                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                        {{ Form::label('email', 'Email address') }}
                        {{ Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'mike@gmail.com']) }}

                        @foreach ($errors->get('email', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>

                <div class="col-2">
                    <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
                        {{ Form::label('phone', 'Phone #') }}
                        {{ Form::text('phone', null, ['class' => 'form-control', 'placeholder' => '8585 123 456']) }}

                        @foreach ($errors->get('phone', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>

                <div class="col-2">
                    <div class="form-group {{ $errors->has('dob') ? 'has-error' : '' }}">
                        {{ Form::label('dob', 'Date of Birth') }}
                        {{ Form::text('dob', null, ['class' => 'form-control', 'placeholder' => '10/17/1980', "data-provide" => "datepicker", "data-date-format" => "mm/dd/yyyy"]) }}

                        @foreach ($errors->get('dob', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>

            </div>


            <div class="row">
                <div class="col-6">
                    <div class="form-group {{ $errors->has('appointment_reason') ? 'has-error' : '' }}">
                        {{ Form::label('appointment_reason', 'Reason for Appointment') }}
                        {{ Form::text('appointment_reason', null, ['class' => 'form-control', 'placeholder' => '']) }}

                        @foreach ($errors->get('appointment_reason', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>


                <div class="col-3">
                    <div class="form-group {{ $errors->has('insurer') ? 'has-error' : '' }}">
                        {{ Form::label('insurer', 'Insurer') }}
                        {{ Form::text('insurer', null, ['class' => 'form-control', 'placeholder' => 'Metlife']) }}

                        @foreach ($errors->get('insurer', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>


                <div class="col-3">
                    <div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}">
                        {{ Form::label('status', 'Status') }}
                        {{ Form::select('status', [\App\Chat::SCHEDULED => "Appointment Scheduled", \App\Chat::NOT_SCHEDULED => "Appointment NOT Scheduled", \App\Chat::FOLLOW_UP_REQUIRED => "Follow-up Required"], null, ['class' => 'form-control', 'placeholder' => 'Status']) }}

                        @foreach ($errors->get('status', []) as $error)
                            <p class="text-danger">{{ $error }}</p>
                        @endforeach
                    </div>
                </div>
            </div>


            <div class="form-group {{ $errors->has('past_medical_history') ? 'has-error' : '' }}">
                {{ Form::label('past_medical_history', 'Past Medical History') }}
                {{ Form::textarea('past_medical_history', null, ['class' => 'form-control', 'placeholder' => '', "rows" => 3]) }}

                @foreach ($errors->get('past_medical_history', []) as $error)
                    <p class="text-danger">{{ $error }}</p>
                @endforeach
            </div>

            <div class="form-group {{ $errors->has('transcript') ? 'has-error' : '' }}">
                {{ Form::label('transcript', 'Chat Transcript') }}
                {{ Form::textarea('transcript', null, ['class' => 'form-control', 'placeholder' => '', "rows" => 15, "style" => "height: auto;"]) }}

                @foreach ($errors->get('transcript', []) as $error)
                    <p class="text-danger">{{ $error }}</p>
                @endforeach
            </div>



            <button class="btn btn-primary">Save</button>
            <a href="{{ route("organizations.chats.index", $organization->id) }}" class="btn btn-link">Cancel</a>

        {{ Form::close() }}
    </div>
</div>
@stop

resources/views/chats/index.blade.php
@extends('layouts.app')

@section("page_title", "Chat for {$organization->name}")

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ route('organizations.index') }}">Organizations</a></li>
    <li class="breadcrumb-item active">Chats for {{ $organization->name }}</li>
</ol>
@stop

@section("content")

    @if(!is_null($chats) and $chats->count() > 0)
        <div class="card-title">
            <div class="row">
                <div class="col-md-4">
                    <form action="{{ route("organizations.chats.index", $organization->id) }}">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" placeholder="Search chat..." value="{{ Request::get("q", "") }}">
                        </div>
                    </form>
                </div>

                <div class="col-md-8 text-right">
                    <a href="{{ route('organizations.chats.create', $organization->id) }}" class="btn btn-link">Add new chat</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Patient</th>
                            <th>Email</th>
                            <th>Phone #</th>
                            <th>DoB</th>
                            <th>Insurer</th>
                            <th>Appointment Reason</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($chats as $chat)
                        <tr>
                            <td><span class="badge badge-{{ str_slug($chat->status) }}">{{ $chat->status }}</span></td>
                            <td>{{ $chat->patient }}</td>
                            <td>{{ $chat->email }}</td>
                            <td>{{ $chat->phone }}</td>
                            <td>{{ $chat->dob }}</td>
                            <td>{{ $chat->insurer }}</td>
                            <td>{{ $chat->appointment_reason }}</td>
                            <td>
                                <ul class="list-inline list-unstyled">
                                    <li class="list-inline-item">
                                        <a href="#" data-chat-trigger="chat-{{ $chat->id }}">
                                            <i class="fa fa-ellipsis-h"></i>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        <tr class="hidden" data-chat-container="chat-{{ $chat->id }}">
                            <td colspan="8" class="text-left">
                                <pre style="height: 500px; white-space: pre-wrap; word-wrap: break-word; font-family: monospace !important; font-size: 1.3rem;">{{ $chat->transcript }}</pre>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>


    @else

        <div class="text-center">
            <p>There are no chats for <strong>{{ $organization->name }}</strong></p>
            <a href="{{ route('organizations.chats.create', $organization->id) }}" class="btn btn-primary">Create first chat</a>
        </div>

    @endif
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div>
    <form class="form">
        <div class="row">
            <div class="col-4">
                <div class="form-group {{ $errors->has('from') ? 'has-error' : '' }}">
                    {{ Form::label('from', 'From') }}
                    {{ Form::text('from', null, ['class' => 'form-control', "data-provide" => "datepicker", "data-date-format" => "mm/dd/yyyy", 'autofocus' => true]) }}

                    @foreach ($errors->get('from', []) as $error)
                        <p class="text-danger">{{ $error }}</p>
                    @endforeach
                </div>
            </div>
            <div class="col-4">
                <div class="form-group {{ $errors->has('to') ? 'has-error' : '' }}">
                    {{ Form::label('to', 'To') }}
                    {{ Form::text('to', null, ['class' => 'form-control', "data-provide" => "datepicker", "data-date-format" => "mm/dd/yyyy"]) }}

                    @foreach ($errors->get('to', []) as $error)
                        <p class="text-danger">{{ $error }}</p>
                    @endforeach
                </div>
            </div>
            <div class="col-4">
                <button class="btn btn-primary" style="margin-top: 35px;">Search</button>
            </div>
        </div>
    </form>
</div>



<div class="row">
@foreach($orgs as $org)
    <div class="col-sm-6 col-md-4">
        <div class="card">
            <div class="card-title">
                <h4 class="text-center">{{ $org->name }} - <strong>{{ $org->chats->count() }}</strong></h4>
            </div>
            <div class="card-body">
            @if($org->chats->count())
                <canvas id="pie-chart-{{ $org->id }}"></canvas>
            @else
                <div class="text-info text-center mt-5">There are no chats for this Dental Office yet.</div>
            @endif
            </div>
        </div>
    </div>

    {{-- <div class="col-md-3">
        <div class="card bg-primary p-20">
            <div class="media widget-ten">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-users fa-3x"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2 class="color-white">{{ $org->chats->count() }}</h2>
                    <p class="m-b-0">Visitors</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card bg-pink p-20">
            <div class="media widget-ten">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-user-plus fa-3x"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2 class="color-white">{{ $org->chats->where('type', 'SCHEDULED')->count() }}</h2>
                    <p class="m-b-0">Appointments Scheduled</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card bg-success p-20">
            <div class="media widget-ten">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-line-chart fa-3x"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2 class="color-white">{{ $org->chats->count() ? $org->chats->where('type', 'SCHEDULED')->count() / $org->chats->count() * 100 : 0 }}%</h2>
                    <p class="m-b-0">Conversion Rate</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card bg-danger p-20">
            <div class="media widget-ten">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-money fa-3x"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2 class="color-white">${{ $org->chats->where('type', 'SCHEDULED')->count() * 1000 }}</h2>
                    <p class="m-b-0">Life Time Value</p>
                </div>
            </div>
        </div>
    </div> --}}
<hr>
@endforeach
</div>

@stop



@section("scripts")
<script type="text/javascript">
@foreach($orgs as $org)
@if($org->chats->count())
var ctx = document.getElementById("pie-chart-{{ $org->id }}");
ctx.height = 300;
var myChart = new Chart( ctx, {
    type: 'pie',
    data: {
        datasets: [ {
            data: [
                {{ $org->chats->where('status', 'SCHEDULED')->count() }},
                {{ $org->chats->where('status', 'NOT_SCHEDULED')->count() }},
                {{ $org->chats->where('status', 'FOLLOW_UP')->count() }}
            ],
            backgroundColor: [
                "rgba({{ abs(($org->id + strlen($org->name)) % 255) }}, {{ abs(($org->id - strlen($org->name)) % 255) }}, {{ abs(($org->id * strlen($org->name)) % 255) }}, 0.9)",
                "rgba({{ abs(($org->id + strlen($org->name)) % 255) }}, {{ abs(($org->id - strlen($org->name)) % 255) }}, {{ abs(($org->id * strlen($org->name)) % 255) }}, 0.6)",
                "rgba({{ abs(($org->id + strlen($org->name)) % 255) }}, {{ abs(($org->id - strlen($org->name)) % 255) }}, {{ abs(($org->id * strlen($org->name)) % 255) }}, 0.3)",
            ],
            hoverBackgroundColor: [
                "rgba({{ abs(($org->id + strlen($org->name)) % 255) }}, {{ abs(($org->id - strlen($org->name)) % 255) }}, {{ abs(($org->id * strlen($org->name)) % 255) }}, 0.9)",
                "rgba({{ abs(($org->id + strlen($org->name)) % 255) }}, {{ abs(($org->id - strlen($org->name)) % 255) }}, {{ abs(($org->id * strlen($org->name)) % 255) }}, 0.6)",
                "rgba({{ abs(($org->id + strlen($org->name)) % 255) }}, {{ abs(($org->id - strlen($org->name)) % 255) }}, {{ abs(($org->id * strlen($org->name)) % 255) }}, 0.3)",
            ]

        } ],
        labels: [
            "Scheduled",
            "Not Scheduled",
            "Follow-up Required"
        ]
},
    options: {
        responsive: true
    }
} );
@endif
@endforeach
</script>
@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield("page_title") - {{ config('app.name', 'Brux Dental Chat') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">

    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link href="{{ asset('css/lib/bootstrap/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/lib/datepicker/bootstrap-datepicker3.min.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    <link href="{{ asset('css/helper.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <style type="text/css">
        * { font-family: 'Open Sans', sans-serif !important;  }
        .fa{
            font-family: 'fontawesome' !important;
        }

        [class^="ti-"], [class*=" ti-"]{
            font-family: 'themify' !important;
        }

        ::placeholder { color: #ccc !important; }
        .badge{
            color: white !important;
        }

        .badge-admin, .badge-not-scheduled{
            background-color: #ef5350;
        }

        .badge-agent, .badge-scheduled{
            background-color: #26dad2;
        }

        .badge-customer, .badge-follow-up-required{
            background-color: #5c4ac7;
        }

        .ellipsis{
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    </style>
</head>
<body>
    <!-- Main wrapper  -->
    <div id="main-wrapper">
        <!-- header header  -->
        <div class="header">
            @include("layouts.navbar")
        </div>
        <!-- End header header -->
        <!-- Left Sidebar  -->
        <div class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                @include("layouts.sidebar")
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </div>
        <!-- End Left Sidebar  -->
        <!-- Page wrapper  -->
        <div class="page-wrapper">
            <!-- Bread crumb -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-primary">@yield("page_title")</h3> </div>
                <div class="col-md-7 align-self-center">
                    @yield('breadcrumbs')
                </div>
            </div>
            <!-- End Bread crumb -->
            <!-- Container fluid  -->
            <div class="container-fluid">
                @yield('content')
            </div>
            <!-- End Container fluid  -->
            <!-- footer -->
            <footer class="footer"> © {{ date('Y') }} All rights reserved. {{ config('app.name') }}</footer>
            <!-- End footer -->
        </div>
        <!-- End Page wrapper  -->
    </div>
    <!-- End Wrapper -->


    <script src="{{ asset('js/lib/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ asset('js/lib/bootstrap/js/popper.min.js') }}"></script>
    <script src="{{ asset('js/lib/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/lib/datepicker/bootstrap-datepicker.min.js') }}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ asset('js/jquery.slimscroll.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('js/sidebarmenu.js') }}"></script>

    <script src="{{ asset('js/lib/chart-js/Chart.bundle.js') }}"></script>

    <script type="text/javascript">
        $('[data-toggle="popover"]').popover({});

        $('[data-chat-trigger]').on('click', function(e){
            e.preventDefault();

            var id = $(this).data('chat-trigger');
            var currentVisibleChatContainer = $('[data-chat-container="'+ id +'"]:visible').data("chat-container");

            $('[data-chat-container]').addClass('hidden');

            if(id != currentVisibleChatContainer){
                $('[data-chat-container="'+ id +'"]').removeClass('hidden');
            }

        });
    </script>

    @yield("scripts")
</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar top-navbar navbar-expand-md navbar-light">
    <!-- Logo -->
    <div class="navbar-header">
        <a class="navbar-brand" href="/">
            <!-- Logo icon -->
           <b><img src="/images/logo.png" alt="homepage" class="dark-logo" /></b>
           <!--End Logo icon -->
           <!-- Logo text -->
           <span><img src="/images/logo-text.png" alt="homepage" class="dark-logo" /></span>
        </a>
    </div>
    <!-- End Logo -->
    <div class="navbar-collapse">
        <ul class="navbar-nav mr-auto mt-md-0">
        </ul>


        <!-- User profile and search -->
        <ul class="navbar-nav my-lg-0">
            <!-- Search -->
            <li class="nav-item hidden-sm-down search-box">
                <a class="nav-link hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-search"></i></a>
                <form class="app-search">
                    <input type="text" class="form-control" placeholder="Search here">
                    <a class="srh-btn"><i class="ti-close"></i></a>
                </form>
            </li>


            <!-- Profile -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="/images/users/5.jpg" alt="user" class="profile-pic" />
                </a>
                <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                    <ul class="dropdown-user">
                        <li><a href="#"><i class="ti-user"></i> Profile</a></li>
                        <li><a href="#"><i class="ti-wallet"></i> Balance</a></li>
                        <li><a href="#"><i class="ti-email"></i> Inbox</a></li>
                        <li><a href="#"><i class="ti-settings"></i> Setting</a></li>
                        <li><a href="#"><i class="fa fa-power-off"></i> Logout</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</nav>